import localFont from "next/font/local";
import AppProvider from "./components/AppContext";
import "./globals.css";
import Header from "./components/layout/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Foody App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <main className='max-w-4xl mx-auto p-4'>
            <AppProvider>
          <Header />
          {children}
          <footer className='border-t p-8 text-center text-gray-500 mt-16'>
             &copy;रV 2024 All rights reserved
      </footer>
      </AppProvider>
      </main>
       
      </body>
    </html>
  );
}
